-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS viini CASCADE;
DROP TABLE IF EXISTS kayttaja CASCADE;
DROP TABLE IF EXISTS rypale CASCADE;
DROP TABLE IF EXISTS kotimaa CASCADE;
DROP TABLE IF EXISTS viinin_rypaleet CASCADE;
DROP TABLE IF EXISTS kayttajan_viinit CASCADE;